name: Java CI with Maven + SonarCloud [develop]

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21.0.4'
        distribution: 'liberica'
        java-package: jdk+fx
        architecture: x64
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: UserInterface
        path: target/*.jar
